default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - commit

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: 'requirements.*\.txt'
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, main, --pattern, release-.*]
      - id: check-added-large-files
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
  # - repo: https://github.com/jazzband/pip-tools
  #   rev: 7.3.0
  #   hooks:
  #     - id: pip-compile
  #       name: pip-compile requirements.txt
  #       args: [-o, requirements.txt, pyproject.toml]
  #       files: ^(pyproject\.toml)$
  #     - id: pip-compile
  #       name: pip-compile requirements_dev.txt
  #       args: [-o, requirements_dev.txt, pyproject.toml, --extra, dev, --extra, doc, --extra, test, -c, requirements.txt]
  #       files: ^(pyproject\.toml)$
